USE [DSAU.Website]
GO

DROP TABLE [dbo].[MediaLink]
GO

CREATE TABLE [dbo].[MediaLink](
	[MediaID] [int] NOT NULL,
	[LinkType] VARCHAR(255) NOT NULL,
	[LinkID] [int] NOT NULL
 CONSTRAINT [PK_MediaLink] PRIMARY KEY CLUSTERED 
(
	[MediaID] ASC,
	[LinkType] ASC,
	[LinkID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MediaLink]  WITH NOCHECK ADD  CONSTRAINT [FK_MediaLink_Media] FOREIGN KEY([MediaID])
REFERENCES [dbo].[Media] ([ID])
GO

ALTER TABLE [dbo].[MediaLink] CHECK CONSTRAINT [FK_MediaLink_Media]
GO